### DISCUSSION TITLE
Command not found 'docker-php-ext-install' from gitlab ci

### DISCUSSION THREAD

**Discussion by MikeAW2010** [mlocati/docker-php-extension-installer#627] [Q&A]
I am running a gitlab ci script which includes the `docker-php-ext-install` command, however; the command fails from the gitlab ci and also from the Ubuntu VM with the returned error:

`ubuntu:~$ docker-php-ext-install soap`
`docker-php-ext-install: command not found`

This is my gitlab ci script.. ..is there anything I could be missing?

````yaml
deploy_to_dev:
  stage: deploy
  image: php:5.6
  allow_failure: true
  tags:
  - arc
  variables:
    PWS_IP: 'x.x.x.x'
  before_script:
  - sudo apt-get update && sudo apt-get install -y libxml2-dev git
  - docker-php-ext-install soap
  script:
  - git config --global http.sslVerify false
  - git diff --name-only origin/DEV | xargs php ./scripts/pws_loadgroovy.php
  only:
   refs:
   - DEV
   variables:
   - $CI_PROJECT_ID == "71"
````
