### DISCUSSION TITLE
[Solved] Cannot get this to work with docker-compose.yml and Dockerfile

### DISCUSSION THREAD

**Discussion by mbootsman** [mlocati/docker-php-extension-installer#663] [Q&A] [answered]
Hey, I like to say sorry in advance. Just started with Docker / docker-compose.
Using Ubuntu 22.04.

I have this `docker-compose.yml` file:
```
version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./php/src/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    image: php:8.1-cli
    networks:
      - internal
    volumes:
      - ./php/src/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge
```
And this `Dockerfile`:
```
FROM php:8.1-cli
ADD default.conf /etc/nginx/conf.d
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions bcmath
```

Here's my `default.conf`:
```
server {
    listen 0.0.0.0:80;
    root /var/www/html;
    location / {
        index index.php;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
    }
}
```

When I execute `docker-compose up` a lot of things happen (too much to paste here) and then I get back to the prompt.
When I execute `docker-compose up` again I get this output:
```
Starting remindme_php_1   ... done
Starting remindme_nginx_1 ... done
Attaching to remindme_php_1, remindme_nginx_1
nginx_1  | Interactive shell
nginx_1  | 
php_1    | Interactive shell
php_1    | 
php_1    | php > nginx_1  | php > remindme_php_1 exited with code 0
remindme_nginx_1 exited with code 0
```
Which leaves me with nothing, as in no webserver running at localhost:8080.

Any help is appreciated. Thanks.
