### ISSUE TITLE
cant run php from crons 

### ISSUE THREAD

**Issue by arcanisgk** [mlocati/docker-php-extension-installer#646]
### Version of install-php-extensions

lastes

### Error description

i have this setup:  https://github.com/arcanisgk/Minos

```bash
FROM php:8.1.11-fpm

WORKDIR "/application"

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions pdo_mysql
RUN install-php-extensions Reflection
RUN install-php-extensions session
RUN install-php-extensions SimpleXML
RUN install-php-extensions SPL
RUN install-php-extensions sqlite3
RUN IPE_GD_WITHOUTAVIF=1 install-php-extensions gd
RUN install-php-extensions curl
RUN install-php-extensions imap
RUN IPE_ICU_EN_ONLY=1 install-php-extensions intl
RUN IPE_ICU_EN_ONLY=1 install-php-extensions http
RUN install-php-extensions json
RUN install-php-extensions mailparse
RUN install-php-extensions mbstring
RUN install-php-extensions readline
RUN install-php-extensions soap
RUN install-php-extensions xml
RUN install-php-extensions xmlrpc
RUN install-php-extensions bz2
RUN install-php-extensions zlib
RUN install-php-extensions dba
RUN install-php-extensions ldap
RUN install-php-extensions xdebug
RUN install-php-extensions @composer

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get update && apt-get -y install --no-install-recommends --fix-missing cron
```

and this yml:

```yaml
version: "3.9"
services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    working_dir: /application
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=1qazxsw22
      - MYSQL_DATABASE=minos
      - MYSQL_USER=minos
      - MYSQL_PASSWORD=1qazxsw22
    ports:
      - "3308:3306"
  webserver:
    container_name: webserver
    image: nginx:latest
    working_dir: /application
    volumes:
      - '.:/application'
      - './conf-example/docker-setup/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8008:80'
    depends_on:
      - mysql
    links:
      - mysql
  php-fpm:
    build: ./
    working_dir: /application
    volumes:
      - '.:/application'
      - './conf-example/docker-setup/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
  crontab-ui:
    ports:
      - '8009:8000'
    image: alseambusher/crontab-ui
    volumes:
      - '.:/application'
    links:
      - webserver
    depends_on:
      - webserver
  dozzle:
    container_name: dozzle-viewer
    hostname: dozzle
    image: amir20/dozzle
    ports:
      - "8010:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
when i add a cron:

![image](https://user-images.githubusercontent.com/1207306/195961848-f070a4c3-e511-4c4d-aec1-791072dc86e3.png)

and try to run i get this error:

![image](https://user-images.githubusercontent.com/1207306/195961863-eeab0e2c-a8d1-4fa2-8cd5-333d3ad9ea90.png)

i have try to use `php `or full path `/usr/bin/php`, checking i find that not exist a cli extension on list of installation... when i try to install cli extension i get this error:

![image](https://user-images.githubusercontent.com/1207306/195961940-ae982643-50c8-4612-8caf-58f8aa725ab0.png)

### Docker image

php:8.1.11-fpm
