### ISSUE TITLE
Install multiple extensions

### ISSUE THREAD

**Issue by MimoudiX** [mlocati/docker-php-extension-installer#738]
Hello this is my Docker question

https://stackoverflow.com/questions/76111683/install-multiple-php-extentions-on-a-docker-container

can your script fix my issue?

**Comment by MimoudiX** [comment]
I tried this 
```
FROM php:7.3.29-apache

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd xdebug
```
Knowing my docker file is :

version: "4"
```
services:
  web:
    image: php:7.3.29-apache
    container_name: phpapache2
    ports:
      - "70:80"
    volumes:
      - ./php:/var/www/html
```

`docker build -t phpapache2 .` 
  
Am i missing something ?
