### ISSUE TITLE
Unable to install sockets ext within Dockerfile

### ISSUE THREAD

**Issue by jsayer101** [mlocati/docker-php-extension-installer#991]
### Version of install-php-extensions

latest

### Error description

Hello,

I'm currently using a Dockerfile that works well but I'm trying to add the sockets extension and it seems that it doesn't work.

I also tried : 
- using a minimal Dockerfile
- using the --no-cache build.
- moving the install sockets ext to another step 
- Installing only the sockets ext
- using newer versions of PHP base image

My minimal compose.yaml
```
  php:
    build:
      dockerfile: ./Dockerfile
      context: .
      target: dev
    volumes:
      - ./src:/app
    extra_hosts:
      - "wsl.docker.internal:${WSL_HOST_IP:-host-gateway}"
```
I'm using `docker compose exec -it php php -m` to output installed extensions.

Strangely, when using the command (`docker compose exec -it php docker-php-ext-install socket`) inside the container it does work.

I'm taking all the hints on how to tackle this issue :smile:

Thanks !

### Docker image

php:7.4-apache

### Minimal Dockerfile

```Dockerfile
FROM php:7.4-apache AS dev
USER root

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions sockets

CMD ["apache2-foreground"]
```
